build:
	javac -cp ./libs/org.eclipse.paho.client.mqttv3-1.1.1.jar:. Subscriber.java SimpleMqttCallBack.java Publisher.java 

run_sub:
	java -cp ./libs/org.eclipse.paho.client.mqttv3-1.1.1.jar:. Subscriber

run_pub:
	java -cp ./libs/org.eclipse.paho.client.mqttv3-1.1.1.jar:. Publisher
